# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: SonarCloudPrepare@1
  displayName: Prepare Sonar Cloud
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'laikha'
    scannerMode: 'MSBuild'
    projectKey: 'laikha_IoC'
    projectName: 'IoC'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  displayName: Update Nuget Packages
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: Build Code
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: Test Fase
  inputs:
    testAssemblyVer2: |
      '**\NUnitTestSchool\**\bin\**\**\*Tests.dll'
      '**\NUnitTestSchool\**\bin\**\**\*Test*.dll'
      '**\NUnitTestSchool\**\bin\**\**\Test*.dll'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: SonarCloudAnalyze@1
  displayName: 'Run Code Analysis'

- task: reportgenerator@5
  displayName: 'CoberturaPipeLine'
  inputs:
    reports: '$(Build.SourcesDirectory)\IoC\Tests\CodeCoverage.xml'
    targetdir: '$(Build.SourcesDirectory)\IoC\Tests\coveragereport'
    verbosity: 'Verbose'
    title: 'CoberturaPipeLine'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage report'
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)\IoC\Tests\CodeCoverage.xml'
    pathToSources: '$(solution)'
    reportDirectory: '$(Build.SourcesDirectory)\IoC\Tests\CoverageReport'


- task: SonarCloudPublish@1
  displayName: Publish Sonar
  inputs:
    pollingTimeoutSec: '300'